webapp/rfid_grooming/config/routes.rb
require 'sidekiq/web'

RfidGrooming::Application.routes.draw do
  resources :heartbeats

  resources :power_readings
	post 'power_readings/upload' => 'power_readings#upload'

	get 'readings/stream' => 'readings#index_stream'
	get 'readings/watch' => 'readings#watch'
	get 'readings/latest_readings' => 'readings#latest_readings'

  resources :comparisons
	post 'comparisons/upload' => 'comparisons#upload'

  get 'intervals' => 'intervals#index'
  get "welcome/index"

  resources :readings  
  resources :tags
  resources :cows

	get 'welcome/get_latest_reading' => 'welcome#get_latest_reading'
	get 'welcome/get_latest_reading_by_pen' => 'welcome#get_latest_reading_by_pen'

  root 'welcome#index'

  

	get 'auth/:provider/callback', to: 'sessions#create'
	get 'auth/failure', to: redirect('/')
	get 'signout', to: 'sessions#destroy', as: 'signout'

	resources :sessions, only: [:create, :destroy]

	mount Sidekiq::Web => '/sidekiq'
end

webapp/rfid_grooming/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

webapp/rfid_grooming/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>                                          
<div class="container-fluid">
	<div class="navbar-header">                                                       
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>                                
      <span class="icon-bar"></span>                                                
      <span class="icon-bar"></span>                                                
      <span class="icon-bar"></span>                                                
    </button>                                                                       
    <%= link_to 'RFID Grooming', root_path, class: 'navbar-brand' %>           
  </div>                                                                            
                                                                                    
  <div class="collapse navbar-collapse">                                            
    <ul class="nav navbar-nav nav-pills">                                           
      <%= render 'layouts/navigation_links' %>                                      
    </ul>                                                                           
  </div>                                                                            
                                                                                    
</div>  

webapp/rfid_grooming/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>                                            

<li class="<%= 'active' if current_page?(cows_path)%>"><%= link_to 'Cows', cows_path %></li>
<li class="<%= 'active' if current_page?(tags_path)%>"><%= link_to 'Tags', tags_path %></li>
<li class="<%= 'active' if current_page?(readings_path)%>"><%= link_to 'RFID Readings', readings_path %></li>
<li class="<%= 'active' if current_page?(intervals_path)%>"><%= link_to 'Intervals', intervals_path %></li>
<li class="<%= 'active' if current_page?(power_readings_path)%>"><%= link_to 'Power Readings', power_readings_path %></li>
<li class="<%= 'active' if current_page?(comparisons_path)%>"><%= link_to 'Comparisons', comparisons_path %></li>
<% if current_user %>
	<p class="navbar-text"><%= current_user.name %> (<%= link_to "Sign out", signout_path, id: "sign_out" %>)
<% else %>
	<li>
		<%= link_to image_tag("Red-signin_Medium_base_44dp.png"), "#{ENV["RAILS_RELATIVE_URL_ROOT"]}/auth/google_oauth2", id: "sign_in" %>
	</li>
<% end %>

webapp/rfid_grooming/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RfidGrooming" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>


	<body class="container-fluid">                                                    
		<div class="navbar navbar-inverse navbar-static-top" role="navigation">          
			<%= render 'layouts/navigation' %>                                            
		</div>                                                                          

		<div class="container-fluid">
				<% if current_user %>
					<%= render 'layouts/messages' %>                                              
					<%= yield %>    
				<% else %>
					<h1>Please sign in.</h1>
				<% end %>
		</div>

		<div id="footer">
			<div class="container-fluid">
				<p class="text-muted">Last updated: September 18, 2014</p>
			</div>
		</div>

	</body>  

</html>