webapp/rfid_grooming/config/routes.rb
require 'sidekiq/web'

RfidGrooming::Application.routes.draw do
  resources :heartbeats

  resources :power_readings
	post 'power_readings/upload' => 'power_readings#upload'

	get 'readings/stream' => 'readings#index_stream'
	get 'readings/watch' => 'readings#watch'
	get 'readings/latest_readings' => 'readings#latest_readings'

  resources :comparisons
	post 'comparisons/upload' => 'comparisons#upload'

  get 'intervals' => 'intervals#index'
  get "welcome/index"

  resources :readings  
  resources :tags
  resources :cows

	get 'welcome/get_latest_reading' => 'welcome#get_latest_reading'
	get 'welcome/get_latest_reading_by_pen' => 'welcome#get_latest_reading_by_pen'

  root 'welcome#index'

  

	get 'auth/:provider/callback', to: 'sessions#create'
	get 'auth/failure', to: redirect('/')
	get 'signout', to: 'sessions#destroy', as: 'signout'

	resources :sessions, only: [:create, :destroy]

	mount Sidekiq::Web => '/sidekiq'
end

webapp/rfid_grooming/app/models/power_reading.rb
class PowerReading < ActiveRecord::Base
end

webapp/rfid_grooming/app/controllers/power_readings_controller.rb
class PowerReadingsController < ApplicationController
  before_action :set_power_reading, only: [:show, :edit, :update, :destroy]

  # GET /power_readings
  # GET /power_readings.json
  def index
 		@search = PowerReading.search(params[:q])                                            
    @power_readings = @search.result.order('time DESC').paginate(:page => params[:page])
  end

  # GET /power_readings/1
  # GET /power_readings/1.json
  def show
  end

  # GET /power_readings/new
  def new
    @power_reading = PowerReading.new
  end

  # GET /power_readings/1/edit
  def edit
  end

  # POST /power_readings
  # POST /power_readings.json
  def create
    @power_reading = PowerReading.new(power_reading_params)

    respond_to do |format|
      if @power_reading.save
        format.html { redirect_to @power_reading, notice: 'Power reading was successfully created.' }
        format.json { render action: 'show', status: :created, location: @power_reading }
      else
        format.html { render action: 'new' }
        format.json { render json: @power_reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /power_readings/1
  # PATCH/PUT /power_readings/1.json
  def update
    respond_to do |format|
      if @power_reading.update(power_reading_params)
        format.html { redirect_to @power_reading, notice: 'Power reading was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @power_reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /power_readings/1
  # DELETE /power_readings/1.json
  def destroy
    @power_reading.destroy
    respond_to do |format|
      format.html { redirect_to power_readings_url }
      format.json { head :no_content }
    end
  end


	def upload
		PowerReadingsWorker.perform_async(params[:uploaded_file].original_filename, params[:uploaded_file].read, params[:pen].to_i)
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_power_reading
      @power_reading = PowerReading.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def power_reading_params
      params.require(:power_reading).permit(:time, :power, :pen)
    end
end

webapp/rfid_grooming/app/helpers/power_readings_helper.rb
module PowerReadingsHelper
end

webapp/rfid_grooming/app/views/power_readings/_form.html.erb
<%= form_for(@power_reading) do |f| %>
  <% if @power_reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@power_reading.errors.count, "error") %> prohibited this power_reading from being saved:</h2>

      <ul>
      <% @power_reading.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :power %><br>
    <%= f.text_field :power %>
  </div>
  <div class="field">
    <%= f.label :pen %><br>
    <%= f.number_field :pen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

webapp/rfid_grooming/app/views/power_readings/edit.html.erb
<h1>Editing power_reading</h1>

<%= render 'form' %>

<%= link_to 'Show', @power_reading %> |
<%= link_to 'Back', power_readings_path %>

webapp/rfid_grooming/app/views/power_readings/index.html.erb
<h1>File Upload</h1>
<p>Upload a CSV file</p>

<%= form_tag({action: :upload}, multipart: true) do %>
	<div class="form-group">                                                      
		<%= label_tag(:pen, "Pen:", class: "control-label") %>
		<% [1, 2].each do |pen| %> 
			<% checked = !params[:pen].nil? and params[:pen].to_i == pen %>
			<div class="radio-inline">
			<%= radio_button_tag 'pen', pen, checked %>
			<%= pen %>
			</div>
		<% end %>
	</div>


	<div class="form-group">
  	<%= file_field_tag 'uploaded_file' %>
	</div>
	<div class="form-group">
		<%= submit_tag("Upload File", class: "btn btn-primary") %> 
	</div>
<% end %>




<h1>Power Readings</h1>
                                                                               
<div class="flickr_pagination">                                                 
  <div class="page_info"><%= page_entries_info @power_readings %></div>              
</div> 

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>ID</th>
      <th>Time</th>
      <th>Power</th>
      <th>Pen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @power_readings.each do |power_reading| %>
      <tr>
        <td><%= power_reading.id %></td>
        <td><%= power_reading.time %></td>
        <td><%= power_reading.power %></td>
        <td><%= power_reading.pen %></td>
        <td><%= link_to 'Show', power_reading %></td>
        <td><%= link_to 'Edit', edit_power_reading_path(power_reading) %></td>
        <td><%= link_to 'Destroy', power_reading, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="flickr_pagination">                                                 
  <div class="page_info"><%= page_entries_info @power_readings %></div>              
  <%= will_paginate @power_readings %>                                               
</div> 

<%= link_to 'New Power reading', new_power_reading_path %>

webapp/rfid_grooming/app/views/power_readings/new.html.erb
<h1>New power_reading</h1>

<%= render 'form' %>

<%= link_to 'Back', power_readings_path %>

webapp/rfid_grooming/app/views/power_readings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @power_reading.time %>
</p>

<p>
  <strong>Power:</strong>
  <%= @power_reading.power %>
</p>

<p>
  <strong>Pen:</strong>
  <%= @power_reading.pen %>
</p>

<%= link_to 'Edit', edit_power_reading_path(@power_reading) %> |
<%= link_to 'Back', power_readings_path %>

webapp/rfid_grooming/app/views/power_readings/upload.html.erb
<h1>Processing file...</h1>