webapp/rfid_grooming/config/routes.rb
require 'sidekiq/web'

RfidGrooming::Application.routes.draw do
  resources :heartbeats

  resources :power_readings
	post 'power_readings/upload' => 'power_readings#upload'

	get 'readings/stream' => 'readings#index_stream'
	get 'readings/watch' => 'readings#watch'
	get 'readings/latest_readings' => 'readings#latest_readings'

  resources :comparisons
	post 'comparisons/upload' => 'comparisons#upload'

  get 'intervals' => 'intervals#index'
  get "welcome/index"

  resources :readings  
  resources :tags
  resources :cows

	get 'welcome/get_latest_reading' => 'welcome#get_latest_reading'
	get 'welcome/get_latest_reading_by_pen' => 'welcome#get_latest_reading_by_pen'

  root 'welcome#index'

  

	get 'auth/:provider/callback', to: 'sessions#create'
	get 'auth/failure', to: redirect('/')
	get 'signout', to: 'sessions#destroy', as: 'signout'

	resources :sessions, only: [:create, :destroy]

	mount Sidekiq::Web => '/sidekiq'
end

webapp/rfid_grooming/app/models/heartbeat.rb
class Heartbeat < ActiveRecord::Base
end

webapp/rfid_grooming/app/controllers/heartbeats_controller.rb
class HeartbeatsController < ApplicationController
  before_action :set_heartbeat, only: [:show, :edit, :update, :destroy]

  # GET /heartbeats
  # GET /heartbeats.json
  def index
    @heartbeats = Heartbeat.all
  end

  # GET /heartbeats/1
  # GET /heartbeats/1.json
  def show
  end

  # GET /heartbeats/new
  def new
    @heartbeat = Heartbeat.new
  end

  # GET /heartbeats/1/edit
  def edit
  end

  # POST /heartbeats
  # POST /heartbeats.json
  def create
    @heartbeat = Heartbeat.new(heartbeat_params)

    respond_to do |format|
      if @heartbeat.save
        format.html { redirect_to @heartbeat, notice: 'Heartbeat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @heartbeat }
      else
        format.html { render action: 'new' }
        format.json { render json: @heartbeat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heartbeats/1
  # PATCH/PUT /heartbeats/1.json
  def update
    respond_to do |format|
      if @heartbeat.update(heartbeat_params)
        format.html { redirect_to @heartbeat, notice: 'Heartbeat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @heartbeat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heartbeats/1
  # DELETE /heartbeats/1.json
  def destroy
    @heartbeat.destroy
    respond_to do |format|
      format.html { redirect_to heartbeats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_heartbeat
      @heartbeat = Heartbeat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def heartbeat_params
      params.require(:heartbeat).permit(:pen, :time)
    end
end

webapp/rfid_grooming/app/helpers/heartbeats_helper.rb
module HeartbeatsHelper
end

webapp/rfid_grooming/app/views/heartbeats/_form.html.erb
<%= form_for(@heartbeat) do |f| %>
  <% if @heartbeat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@heartbeat.errors.count, "error") %> prohibited this heartbeat from being saved:</h2>

      <ul>
      <% @heartbeat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pen %><br>
    <%= f.number_field :pen %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

webapp/rfid_grooming/app/views/heartbeats/edit.html.erb
<h1>Editing heartbeat</h1>

<%= render 'form' %>

<%= link_to 'Show', @heartbeat %> |
<%= link_to 'Back', heartbeats_path %>

webapp/rfid_grooming/app/views/heartbeats/index.html.erb
<h1>Listing heartbeats</h1>

<table>
  <thead>
    <tr>
      <th>Pen</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @heartbeats.each do |heartbeat| %>
      <tr>
        <td><%= heartbeat.pen %></td>
        <td><%= heartbeat.time %></td>
        <td><%= link_to 'Show', heartbeat %></td>
        <td><%= link_to 'Edit', edit_heartbeat_path(heartbeat) %></td>
        <td><%= link_to 'Destroy', heartbeat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Heartbeat', new_heartbeat_path %>

webapp/rfid_grooming/app/views/heartbeats/new.html.erb
<h1>New heartbeat</h1>

<%= render 'form' %>

<%= link_to 'Back', heartbeats_path %>

webapp/rfid_grooming/app/views/heartbeats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pen:</strong>
  <%= @heartbeat.pen %>
</p>

<p>
  <strong>Time:</strong>
  <%= @heartbeat.time %>
</p>

<%= link_to 'Edit', edit_heartbeat_path(@heartbeat) %> |
<%= link_to 'Back', heartbeats_path %>