webapp/rfid_grooming/config/routes.rb
require 'sidekiq/web'

RfidGrooming::Application.routes.draw do
  resources :heartbeats

  resources :power_readings
	post 'power_readings/upload' => 'power_readings#upload'

	get 'readings/stream' => 'readings#index_stream'
	get 'readings/watch' => 'readings#watch'
	get 'readings/latest_readings' => 'readings#latest_readings'

  resources :comparisons
	post 'comparisons/upload' => 'comparisons#upload'

  get 'intervals' => 'intervals#index'
  get "welcome/index"

  resources :readings  
  resources :tags
  resources :cows

	get 'welcome/get_latest_reading' => 'welcome#get_latest_reading'
	get 'welcome/get_latest_reading_by_pen' => 'welcome#get_latest_reading_by_pen'

  root 'welcome#index'

  

	get 'auth/:provider/callback', to: 'sessions#create'
	get 'auth/failure', to: redirect('/')
	get 'signout', to: 'sessions#destroy', as: 'signout'

	resources :sessions, only: [:create, :destroy]

	mount Sidekiq::Web => '/sidekiq'
end

webapp/rfid_grooming/app/models/tag.rb
class Tag < ActiveRecord::Base
	belongs_to :cow
	# The readings table has a tag_epc column, compare that with the tag's epc
	has_many :readings, :foreign_key => :tag_epc, :primary_key => :epc

	self.inheritance_column = nil

	def latest_reading
		return Reading.where(:tag_epc => self.epc).order("time DESC").first
	end

	def select_option
		"#{id} - #{epc}"
	end
end

webapp/rfid_grooming/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.order(:id).all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
		@readings = Reading.where(:tag_epc => @tag.epc).order("time DESC").paginate(:page => params[:page])
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
		puts tag_params.inspect
		date_on = DateTime.new(params["from"]["(1i)"].to_i,                        
			params["from"]["(2i)"].to_i,                                                
			params["from"]["(3i)"].to_i,                                                
			params["from"]["(4i)"].to_i,                                                
			params["from"]["(5i)"].to_i)                                                
		date_off = DateTime.new(params["to"]["(1i)"].to_i,                            
			params["to"]["(2i)"].to_i,                                                  
			params["to"]["(3i)"].to_i,                                                  
			params["to"]["(4i)"].to_i,                                                  
			params["to"]["(5i)"].to_i)  
    @tag = Tag.new(tag_params)
		@tag.date_on = date_on
		@tag.date_off = date_off

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tag }
      else
        format.html { render action: 'new' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
		date_on = DateTime.new(params["from"]["(1i)"].to_i,                             
      params["from"]["(2i)"].to_i,                                                  
      params["from"]["(3i)"].to_i,                                                  
      params["from"]["(4i)"].to_i,                                                  
      params["from"]["(5i)"].to_i)                                                  
    date_off = DateTime.new(params["to"]["(1i)"].to_i,                              
      params["to"]["(2i)"].to_i,                                                    
      params["to"]["(3i)"].to_i,                                                    
      params["to"]["(4i)"].to_i,                                                    
      params["to"]["(5i)"].to_i)                                                    
    params["tag"]["date_on"] = date_on
    params["tag"]["date_off"] = date_off
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:epc, :tag_type, :cow_id, :position, :date_on, :date_off)
    end
end

webapp/rfid_grooming/app/helpers/tags_helper.rb
module TagsHelper
end

webapp/rfid_grooming/app/views/tags/_form.html.erb
<div class="well">
<%= form_for(@tag, html: {:class => "form-centered", role: "form"}) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :epc, class: "control-label" %>
    <%= f.text_field :epc, :class => "input-xxlarge form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :tag_type, class: "control-label" %>
		<%= f.select :tag_type, options_for_select(["Squig", "Square", "Sit", "Short"], @tag.tag_type), {}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :cow_id, class: "control-label" %>
    <%= f.collection_select :cow_id, Cow.all, :id, :select_option, {}, {class: "form-control"} %>                
  </div>                                                                            

  <div class="form-group">
    <%= f.label :position, class: "control-label" %>
    <%= f.text_field :position, class: "form-control" %>
  </div>

  <div class="form-group">                                                          
    <%= label_tag(:date_on, "Date On:", class: "control-label") %>              
    <%= datetime_select "from", "", default: @tag.date_on, class: "form-control" %>                          
  </div>                                                                            
                                                                                    
  <div class="form-group">                                                          
    <%= label_tag(:date_off, "Date Off:", class: "control-label") %>                  
    <%= datetime_select "to", "", default: @tag.date_off %>                              
  </div>  


  <div class="actions">
    <%= f.submit "Update", :class => "btn btn-primary form-control" %>
  </div>
<% end %>
</div>

webapp/rfid_grooming/app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

webapp/rfid_grooming/app/views/tags/index.html.erb
<h1>Tags</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>ID</th>
      <th>EPC</th>
      <th>Type</th>
			<th>Cow</th>
			<th>Position</th>
			<th>Date On</th>
			<th>Date Off</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.id %></td>
        <td><%= tag.epc %></td>
        <td><%= tag.tag_type %></td>
        <td><%= tag.cow.nil? ? "" : tag.cow.select_option %></td>
        <td><%= tag.position  %></td>
        <td><%= tag.date_on.to_s(:db) if !tag.date_on.nil? %></td>
        <td><%= tag.date_off.to_s(:db) if !tag.date_off.nil? %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

webapp/rfid_grooming/app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

webapp/rfid_grooming/app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Tag</h1>

<table class="table table-striped table-bordered table-condensed">                  
  <tr>                                                                              
    <th>ID</th>                                                                     
    <td><%= @tag.id %></td>                                                     
  </tr>                                                                             
                                                                                    
  <tr>                                                                              
    <th>EPC</th>                                                                   
    <td><%= @tag.epc %></td>                                                   
  </tr>                                                                             
                                                                                    
  <tr>                                                                              
    <th>Type</th>                                                                
    <td><%= @tag.tag_type %></td>                                                
  </tr>                                                                             
                                                                                    
  <tr>                                                                              
    <th>Cow ID</th>                                                                
    <td><%= @tag.cow.select_option %></td>                                                
  </tr>                                                                             

  <tr>
    <th>Position</th>
    <td><%= @tag.position %></td>
  </tr>                                                                             

	<tr>
    <th>Date On</th>
    <td><%= @tag.date_on %></td>
  </tr> 

	<tr>
    <th>Date Off</th>
    <td><%= @tag.date_off %></td>
  </tr> 
</table>  

<h1>Tag Readings</h1>

<table class="table table-striped table-bordered table-condensed">                  
	<tr>
		<th>ID</th>
		<th>Time</th>
		<th>EPC</th>
		<th>Antenna</th>
		<th colspan="3">Actions</th>
	</tr>
	<% @readings.each do |reading| %>
		<tr>
			<td><%= reading.id %></td>
			<td><%= reading.time %></td>
			<td><%= reading.tag_epc %></td>
			<td><%= reading.antenna %></td>
 			<td><%= link_to 'Show', reading %></td>                                     
     	<td><%= link_to 'Edit', edit_reading_path(reading) %></td>                  
     	<td><%= link_to 'Destroy', reading, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

<div class="apple_pagination">                                                      
  <div class="page_info"><%= page_entries_info @readings %></div>                   
  <%= will_paginate @readings %>                                                    
</div> 

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>